---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-bareos_webui
      bareos_webui_directors:
        - name: localhost-dir
          enabled: yes
          diraddress: localhost
      bareos_webui_configuration:
        - section: session
          option: timeout
          value: 3600
