---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.bareos_webui
      bareos_webui_directors:
        - name: localhost-dir
          enabled: true
          diraddress: localhost
        - name: disabled-dir
          enabled: false
