---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check http://localhost/bareos-webui/
      ansible.builtin.uri:
        url: http://localhost/bareos-webui/
        status_code: 200
        timeout: 5
        return_content: true
      register: bareos_webui_output
      failed_when: "'<title>Bareos - Login</title>' not in bareos_webui_output.content"
